export const MenuIconApperance = {
    Colloid: {
        Calculator: "./colloid/calc.svg",
        ToDo: "./colloid/todo.svg",
        Settings: "./colloid/settings.svg",
        Gallery: "./colloid/gallery.svg",
        Browser: "./colloid/browser.svg",
        Notes: "./colloid/notes.svg",
        Camera: "./colloid/camera.svg",
        MusicPlayer: "./colloid/music.svg",
        YouTube: "./colloid/youtube.svg",
        Games: "./colloid/games.svg",
        FileManager: "./colloid/file-manager.svg",
    },
    Deepin: {
        Calculator: "./Deepin/calc.svg",
        ToDo: "./Deepin/todo.svg",
        Settings: "./Deepin/settings.svg",
        Gallery: "./Deepin/gallery.svg",
        Browser: "./Deepin/browser.svg",
        Notes: "./Deepin/notes.svg",
        Camera: "./Deepin/camera.svg",
        MusicPlayer: "./Deepin/music.svg",
        YouTube: "./Deepin/youtube.svg",
        Games: "./Deepin/games.svg",
        FileManager: "./Deepin/file-manager.svg",
    },
    Fluent: {
        Calculator: "./Fluent/calc.svg",
        ToDo: "./Fluent/todo.svg",
        Settings: "./Fluent/settings.svg",
        Gallery: "./Fluent/gallery.svg",
        Browser: "./Fluent/browser.svg",
        Notes: "./Fluent/notes.svg",
        Camera: "./Fluent/camera.svg",
        MusicPlayer: "./Fluent/music.svg",
        YouTube: "./Fluent/youtube.svg",
        Games: "./Fluent/games.svg",
        FileManager: "./Fluent/file-manager.svg",
    },
    MacTahoe: {
        Calculator: "./MacTahoe/calc.svg",
        ToDo: "./MacTahoe/todo.svg",
        Settings: "./MacTahoe/settings.svg",
        Gallery: "./MacTahoe/gallery.svg",
        Browser: "./MacTahoe/browser.svg",
        Notes: "./MacTahoe/notes.svg",
        Camera: "./MacTahoe/camera.svg",
        MusicPlayer: "./MacTahoe/music.svg",
        YouTube: "./MacTahoe/youtube.svg",
        Games: "./MacTahoe/games.svg",
        FileManager: "./MacTahoe/file-manager.svg",
    },
    WhiteSur: {
        Calculator: "./WhiteSur/calc.svg",
        ToDo: "./WhiteSur/todo.svg",
        Settings: "./WhiteSur/settings.svg",
        Gallery: "./WhiteSur/gallery.svg",
        Browser: "./WhiteSur/browser.svg",
        Notes: "./WhiteSur/notes.svg",
        Camera: "./WhiteSur/camera.svg",
        MusicPlayer: "./WhiteSur/music.svg",
        YouTube: "./WhiteSur/youtube.svg",
        Games: "./WhiteSur/games.svg",
        FileManager: "./WhiteSur/file-manager.svg",
    }
}